[project]
name = "protoweaver-worker"
version = "0.1.0"
description = "Background worker for ProtoWeaver"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=1.10,<2.0",
    "tenacity>=8.2.3",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
